### ISSUE TITLE
What contains the custom box?

### ISSUE THREAD

**Issue by valentin-nasta** [kurron/jvm-development-environment#7]
Hi @kurron,

I see there is used a custom vagrant box, what has this special box beside what the official ubuntu vagrant image provide?

config.vm.box_url = "https://d2eko4jw6kz4m.cloudfront.net/5.0.22/xenial-x64-desktop.box"

**Comment by kurron** [comment]
I build a new box anytime an update to VirtualBox comes out.  The only thing in the base box are the new Guest Additions and the current kernel. I run apt-get dist-upgrade as part of the rebuild process.  I also install Ubuntu using the virtual machine settings so that Ubuntu knows it isn't running on bare metal.
